config/routes.rb
Rails.application.routes.draw do
  resources :events

  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, only: [:show, :edit, :update, :destroy]
  def index
    @events = Event.all
  end 

  def show
  end 

  def new 
    @event = Event.new
  end 

  def create 
    @event = Event.new(event_params)
    if(@event.save)
      redirect_to @event
    else
      render :new
    end 
  end 

  def edit 

  end 

  def update 
    if (@event.update(event_params))
        redirect_to @event
    else 
      render :edit
    end 
  end 

  def destroy 
    @event.delete

    redirect_to events_path
  end 

  private 

  def event_params 
    params.require(:event).permit(:name, :location, :notes)
  end 

  def find_event
    @event = Event.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Upload an Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>All Events</h1>

<% @events.each do |event| %>
<p>
<%= event.name %>
<%= link_to 'View', event_path(event) %> 
<%= link_to 'Edit', edit_event_path(event) %>
<%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/events/new.html.erb
<h1> New Event</h1>

<%= render 'form' %>

<%= link_to 'back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></p></h1>
<h3><%= @event.location  %></h3>
<p><%= @event.notes %></p>

<%= link_to 'back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventApp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>